import fs from 'fs';
import { execSync } from 'child_process';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// 1. Fetch original 100 city pages from git HEAD
const gitRaw = execSync('git show HEAD:frontend/src/data/cityPages.json', { 
  encoding: 'utf-8', 
  maxBuffer: 15 * 1024 * 1024 
});
const original100Pages = JSON.parse(gitRaw);

// 2. Define the 17 City x Category Matrix Pages
const matrixPages = [
  {
    slug: '/power-mosfets-supplier-mumbai',
    city: 'Mumbai (Power MOSFETs)',
    state: 'Maharashtra',
    isHQ: true,
    h1: 'Power MOSFETs Supplier & Stockist in Mumbai',
    metaTitle: 'Power MOSFETs Supplier Mumbai | Mirai Technologies HQ',
    metaDescription: 'Buy N-channel & P-channel Power MOSFETs in Mumbai (IRFP460, IRFP4668, STP55NF06). Walk-in counter pickup at Lamington Rd area, same-day delivery, GST invoice.',
    primaryKeyword: 'power mosfets supplier mumbai',
    secondaryKeywords: 'mosfet stockist mumbai, buy irfp460 mumbai, to247 mosfet supplier lamington road',
    heroContent: 'Mirai Technologies stocks N-channel and P-channel power MOSFETs (30V to 1500V) in TO-220 and TO-247 packages at our Mumbai warehouse for immediate walk-in counter pickup or same-day local dispatch.',
    introduction: 'Need genuine power MOSFETs in Mumbai today? Mirai Technologies maintains physical stock of high-current, high-voltage N-channel and P-channel MOSFETs at our Wadia Street office (Near Lamington Road). Avoid counterfeit risks and long delivery delays by picking up factory-tested parts directly from our counter or requesting same-day delivery across MMR.\n\nFeatured MOSFET Lines in Stock:\n- IRFP460 (500V 20A TO-247 N-Channel MOSFET)\n- IRFP4668 (200V 130A TO-247 High-Current MOSFET)\n- STP55NF06 (60V 50A TO-220 N-Channel MOSFET)\n- IRF3205 (55V 110A Low-Rds MOSFET for Inverters)',
    whyMirai: 'Mumbai counter pickup available today for power MOSFETs. (1) Original manufacturer batch codes. (2) GST tax invoice on all orders. (3) Counter open Mon-Sat. Call +91 93213 98188.',
    productCategories: 'Full range of power MOSFETs in TO-220, TO-247, and SOT-23 packages available in Mumbai.',
    targetIndustries: 'Inverter Repair, Power Electronics, Panel Building, R&D Labs',
    industriesWeServe: 'Serving power electronics engineers across Mumbai, Thane, and Navi Mumbai.',
    faqs: [{ q: 'Can I buy single-piece MOSFETs at your Mumbai counter?', a: 'Yes, counter pickup in Mumbai has zero MOQ on stock power MOSFETs.' }],
    internalLinks: 'All MOSFETs|/products/mosfet-transistor|Mumbai HQ|/electronic-components-supplier-mumbai',
    canonicalUrl: 'https://miraitechnologies.net/power-mosfets-supplier-mumbai',
    robotsMeta: 'index, follow'
  },
  {
    slug: '/igbts-supplier-mumbai',
    city: 'Mumbai (IGBTs)',
    state: 'Maharashtra',
    isHQ: true,
    h1: 'IGBTs & Power Transistors Supplier in Mumbai',
    metaTitle: 'IGBT Supplier Mumbai | Mirai Technologies HQ Stockist',
    metaDescription: 'Buy high-voltage IGBTs (600V-1200V) in Mumbai (FGL60N100, 75N60). Walk-in counter at Lamington Rd area, same-day delivery, GST invoice.',
    primaryKeyword: 'igbts supplier mumbai',
    secondaryKeywords: 'igbt stockist mumbai, welding machine igbt mumbai, fgl60n100 supplier lamington road',
    heroContent: 'Physical stock of discrete IGBTs (600V-1200V, 30A-100A) for welding machine repair, solar inverters, and motor drives available for immediate pickup in Mumbai.',
    introduction: 'Mirai Technologies is a direct stockist of discrete IGBTs and high-power switching transistors in Mumbai. Electronics repair technicians and power panel builders around Lamington Road rely on our physical counter stock of FGL60N100, 75N60, and high-frequency IGBTs.\n\nFeatured IGBT Lines in Stock:\n- FGL60N100 (1000V 60A NPT Trench IGBT)\n- 75N60 / 60N60 (600V 75A Fast-Switching IGBT)\n- TO-247 power packages for heavy-duty thermal mounting',
    whyMirai: 'Walk-in counter pickup in Mumbai. Genuine stock with original manufacturer markings. Contact: sales@miraitechnologies.net.',
    productCategories: '600V to 1200V IGBTs in TO-247 package held in Mumbai inventory.',
    targetIndustries: 'Welding Machine Repair, Solar Inverters, VFD Repair, Power Panels',
    industriesWeServe: 'Serving repair workshops and panel builders across Mumbai Metropolitan Region.',
    faqs: [{ q: 'Do you stock welding inverter IGBTs in Mumbai?', a: 'Yes, we stock FGL60N100 and 60N60 IGBTs widely used in inverter welding machines.' }],
    internalLinks: 'All IGBTs|/products/igbts|Mumbai HQ|/electronic-components-supplier-mumbai',
    canonicalUrl: 'https://miraitechnologies.net/igbts-supplier-mumbai',
    robotsMeta: 'index, follow'
  },
  {
    slug: '/integrated-circuits-supplier-mumbai',
    city: 'Mumbai (ICs)',
    state: 'Maharashtra',
    isHQ: true,
    h1: 'Integrated Circuits (ICs) Supplier in Mumbai',
    metaTitle: 'Integrated Circuits Supplier Mumbai | Mirai Technologies HQ',
    metaDescription: 'Shop 270+ ICs in Mumbai: Op-amps, comparators, optocouplers, logic & interface ICs (LM358, LM339, ULN2003). Counter pickup at Lamington Rd area.',
    primaryKeyword: 'integrated circuits supplier mumbai',
    secondaryKeywords: 'ic distributor mumbai, op amp supplier lamington road, buy lm358 mumbai',
    heroContent: 'Mirai Technologies stocks 270+ active integrated circuit line items at our Mumbai warehouse, including operational amplifiers, comparators, interface ICs, and microcontrollers.',
    introduction: 'Sourcing genuine integrated circuits in Mumbai is simple with Mirai Technologies. We stock linear ICs, logic gates, real-time clocks, and USB transceivers in DIP through-hole and SOIC surface-mount packages. Visit our Mumbai sales office near Lamington Road for instant order fulfillment.\n\nPopular IC Lines in Mumbai Warehouse:\n- LM358 / LM358L (Dual Operational Amplifier)\n- LM339 / LM339L (Quad Voltage Comparator)\n- ULN2003 / ULN2008 (Darlington Transistor Array)\n- CH340G (USB to Serial Interface IC)\n- DS1307 (Real Time Clock IC)',
    whyMirai: 'Immediate pickup at our Mumbai office. 100% inspected stock. Call +91 93213 98188.',
    productCategories: 'Linear ICs, Logic ICs, Microcontrollers, and Interface ICs in stock.',
    targetIndustries: 'Industrial Controls, R&D Labs, Consumer Repairs, Automation',
    industriesWeServe: 'Serving OEMs, labs, and repair engineers in Mumbai, Thane, and Navi Mumbai.',
    faqs: [{ q: 'Are both DIP and SMD package ICs available in Mumbai?', a: 'Yes, we stock both through-hole DIP and surface-mount SOIC/SOP packages.' }],
    internalLinks: 'All ICs|/products/integrated-circuit|Mumbai HQ|/electronic-components-supplier-mumbai',
    canonicalUrl: 'https://miraitechnologies.net/integrated-circuits-supplier-mumbai',
    robotsMeta: 'index, follow'
  },
  {
    slug: '/microcontrollers-supplier-mumbai',
    city: 'Mumbai (Microcontrollers)',
    state: 'Maharashtra',
    isHQ: true,
    h1: 'Microcontrollers Supplier & Stockist in Mumbai',
    metaTitle: 'Microcontrollers Supplier Mumbai | Mirai Technologies HQ',
    metaDescription: 'Buy 8-bit & 32-bit Microcontrollers in Mumbai. Counter pickup at Lamington Rd area, zero MOQ sample orders, GST invoice, same-day delivery.',
    primaryKeyword: 'microcontrollers supplier mumbai',
    secondaryKeywords: 'mcu stockist mumbai, microcontroller supplier lamington road, buy microcontrollers mumbai',
    heroContent: 'Mirai Technologies provides 8-bit, 16-bit, and 32-bit microcontrollers from Mumbai inventory for prototype developers and B2B production lines.',
    introduction: 'Mirai Technologies stocks microcontrollers for embedded hardware engineers and product developers across Mumbai. Sourcing from our physical inventory ensures authentic silicon with verified date codes and fast counter pickup.\n\nFeatured Microcontroller Sourcing:\n- 8-bit and 32-bit MCUs in DIP, QFP, and SOP packages\n- Compatible clock crystal oscillators and RTC peripheral ICs\n- Zero minimum order quantity on catalog MCU lines',
    whyMirai: 'Counter pickup at Mumbai sales office. Complete datasheet verification. Contact: sales@miraitechnologies.net.',
    productCategories: 'Microcontrollers, RTCs, and memory ICs available in Mumbai.',
    targetIndustries: 'Embedded Hardware, Smart Metering, IoT Devices, Educational R&D',
    industriesWeServe: 'Supporting hardware developers across Mumbai Metropolitan Region.',
    faqs: [{ q: 'Can I purchase small quantities of MCUs for prototyping in Mumbai?', a: 'Yes, we support single-piece sample orders for local MCU developers.' }],
    internalLinks: 'All Microcontrollers|/products/microcontrollers|Mumbai HQ|/electronic-components-supplier-mumbai',
    canonicalUrl: 'https://miraitechnologies.net/microcontrollers-supplier-mumbai',
    robotsMeta: 'index, follow'
  },
  {
    slug: '/transistors-optocouplers-supplier-mumbai',
    city: 'Mumbai (Optocouplers)',
    state: 'Maharashtra',
    isHQ: true,
    h1: 'Transistors & Optocouplers Supplier in Mumbai',
    metaTitle: 'Transistors & Optocouplers Supplier Mumbai | Mirai Tech',
    metaDescription: 'Buy Optocouplers (PC817, 4N33M, MOC3021) & Bipolar Transistors in Mumbai. Lamington Rd area counter pickup, same-day delivery, GST invoice.',
    primaryKeyword: 'optocouplers supplier mumbai',
    secondaryKeywords: 'pc817 optocoupler mumbai, transistor supplier lamington road, moc3021 optocoupler supplier mumbai',
    heroContent: 'Physical stock of optical isolators (PC817, MOC3021, 4N33M) and bipolar power transistors available for immediate pickup at our Mumbai office.',
    introduction: 'Optical isolators and power transistors are essential for isolating control logic from high-voltage power noise. Mirai Technologies stocks phototransistor optocouplers, TRIAC drivers, and bipolar power transistors in DIP and SMD packages in Mumbai.\n\nKey Items in Stock in Mumbai:\n- PC817 / PC817C (Phototransistor Optocoupler)\n- MOC3021 / MOC3023M (Random-Phase TRIAC Driver Optocoupler)\n- 4N33M (Darlington Optocoupler)\n- TIP122 / TIP127 (Darlington Power Transistors)',
    whyMirai: 'Immediate Mumbai counter fulfillment. 100% factory original parts. Call +91 93213 98188.',
    productCategories: 'Optocouplers, TRIAC drivers, Darlington pairs, and bipolar transistors.',
    targetIndustries: 'Industrial Control Panels, SMPS Repair, Motor Controllers, Home Appliances',
    industriesWeServe: 'Supplying electronics assembly units and repair engineers in Mumbai.',
    faqs: [{ q: 'Do you stock PC817 optocouplers in bulk in Mumbai?', a: 'Yes, PC817 optocouplers are held in high volume stock in our Mumbai warehouse.' }],
    internalLinks: 'All Optocouplers|/products/optocouplers|Mumbai HQ|/electronic-components-supplier-mumbai',
    canonicalUrl: 'https://miraitechnologies.net/transistors-optocouplers-supplier-mumbai',
    robotsMeta: 'index, follow'
  },
  {
    slug: '/voltage-regulators-supplier-mumbai',
    city: 'Mumbai (Regulators)',
    state: 'Maharashtra',
    isHQ: true,
    h1: 'Voltage Regulators Supplier & Stockist in Mumbai',
    metaTitle: 'Voltage Regulators Supplier Mumbai | Mirai Technologies',
    metaDescription: 'Buy Linear Voltage Regulators (LM7805, LM7812, LM317) & LDOs in Mumbai. Counter pickup at Lamington Rd area, same-day dispatch.',
    primaryKeyword: 'voltage regulators supplier mumbai',
    secondaryKeywords: 'lm7805 supplier mumbai, 7812 regulator lamington road, ldo regulator stockist mumbai',
    heroContent: 'Fixed and adjustable linear voltage regulators (LM7805, LM7812, LM317, LM1117) available from Mumbai warehouse inventory.',
    introduction: 'Mirai Technologies maintains high-volume inventory of standard linear power regulators and low-dropout (LDO) regulator ICs in TO-220 and SOT-223 packages at our Mumbai sales center.\n\nFeatured Voltage Regulators in Stock:\n- LM7805 / L7805CV (5V 1.5A Positive Voltage Regulator)\n- LM7812 / L7812CV (12V 1.5A Positive Voltage Regulator)\n- LM317T (1.2V-37V Adjustable Voltage Regulator)\n- AMS1117 / LM1117 (3.3V / 5.0V LDO Regulators)',
    whyMirai: 'Immediate Mumbai pickup. Full GST tax invoices. Contact sales@miraitechnologies.net.',
    productCategories: 'Linear 78xx series, 79xx series, LM317, and SMD LDO regulators in Mumbai.',
    targetIndustries: 'Power Supplies, Battery Chargers, Embedded Systems, Automation',
    industriesWeServe: 'Serving power supply builders and electronics workshops across Mumbai.',
    faqs: [{ q: 'Are 7805 regulators available in TO-220 and SMD packages in Mumbai?', a: 'Yes, we stock both TO-220 through-hole and SOT-223/TO-252 SMD packages.' }],
    internalLinks: 'All Regulators|/products/integrated-circuit|Mumbai HQ|/electronic-components-supplier-mumbai',
    canonicalUrl: 'https://miraitechnologies.net/voltage-regulators-supplier-mumbai',
    robotsMeta: 'index, follow'
  },
  {
    slug: '/diodes-rectifiers-supplier-mumbai',
    city: 'Mumbai (Diodes)',
    state: 'Maharashtra',
    isHQ: true,
    h1: 'Diodes & Bridge Rectifiers Supplier in Mumbai',
    metaTitle: 'Diodes & Bridge Rectifiers Supplier Mumbai | Mirai Tech',
    metaDescription: 'Buy Bridge Rectifiers (MB6S, MB10S), Schottky Diodes & Zeners in Mumbai. Counter pickup at Lamington Rd area, same-day delivery, GST invoice.',
    primaryKeyword: 'diodes rectifiers supplier mumbai',
    secondaryKeywords: 'bridge rectifier supplier mumbai, mb6s stockist lamington road, schottky diode mumbai',
    heroContent: 'Single-phase bridge rectifiers, Schottky diodes, Zener diodes, and fast recovery rectifiers in stock in Mumbai for immediate order fulfillment.',
    introduction: 'Power supply rectification requires reliable diodes that handle high surges without thermal breakdown. Mirai Technologies stocks SMD bridge rectifiers (MB6S, MB10S) and through-hole power rectifiers in Mumbai.\n\nFeatured Rectifiers in Mumbai Stock:\n- MB6S / MB10S (0.5A 600V/1000V SMD Bridge Rectifiers)\n- 1N4007 / 1N5408 (Standard Recovery Rectifier Diodes)\n- SR560 / SS34 (Schottky Barrier Diodes)',
    whyMirai: 'Mumbai counter stock. Instant dispatch across MMR. Call +91 93213 98188.',
    productCategories: 'SMD and through-hole bridge rectifiers, Schottky, and Zener diodes.',
    targetIndustries: 'LED Drivers, Power Adapter Assembly, Industrial Chargers',
    industriesWeServe: 'Supplying power supply manufacturers across Mumbai, Thane, and Navi Mumbai.',
    faqs: [{ q: 'Do you stock MB6S bridge rectifiers in full reel packaging in Mumbai?', a: 'Yes, MB6S and MB10S are available in full 3,000-piece tape & reel as well as cut tape.' }],
    internalLinks: 'All Diodes|/products/diodes-rectifiers|Mumbai HQ|/electronic-components-supplier-mumbai',
    canonicalUrl: 'https://miraitechnologies.net/diodes-rectifiers-supplier-mumbai',
    robotsMeta: 'index, follow'
  },
  {
    slug: '/power-mosfets-supplier-pune',
    city: 'Pune (Power MOSFETs)',
    state: 'Maharashtra',
    isHQ: false,
    h1: 'Power MOSFETs Supplier for Pune Automotive & EV Sector',
    metaTitle: 'Power MOSFETs Supplier Pune | Mirai Technologies',
    metaDescription: 'Power MOSFET supplier for Pune automotive & EV clusters in Chakan & Bhosari (IRFP4668, IRFP460, STP55NF06). 24-48h courier delivery from Mumbai.',
    primaryKeyword: 'power mosfets supplier pune',
    secondaryKeywords: 'ev mosfet supplier pune, chakan mosfet distributor, irfp4668 pune',
    heroContent: 'High-current N-channel and P-channel power MOSFETs dispatched from Mumbai to Pune automotive and EV manufacturing hubs in 24 to 48 hours.',
    introduction: 'Engineers designing EV motor controllers and DC-DC power stages in Chakan and Bhosari require low-Rds(on) power MOSFETs capable of switching high current with minimal thermal loss. Mirai Technologies provides tested power MOSFETs with 24-48 hour delivery to Pune.\n\nKey MOSFET Lines for Pune Automotive Industry:\n- IRFP4668 (200V 130A N-Channel MOSFET for EV motor drives)\n- IRFP460 (500V 20A TO-247 MOSFET for industrial power supplies)\n- STP55NF06 (60V 50A TO-220 MOSFET for automotive body control)',
    whyMirai: 'Direct dispatch to Pune industrial units. Full GST tax invoices & e-way bills. Contact: sales@miraitechnologies.net.',
    productCategories: 'TO-220, TO-247, and D2PAK power MOSFETs supplied to Pune.',
    targetIndustries: 'EV Charger Manufacturing, Automotive Tier-1, Motor Drives',
    industriesWeServe: 'Serving manufacturing units in Chakan, Ranjangaon, Bhosari, and Hinjawadi.',
    faqs: [{ q: 'What is the delivery time for power MOSFETs to Chakan industrial zone?', a: 'Standard courier shipments reach Chakan in 24 to 48 hours from our Mumbai warehouse.' }],
    internalLinks: 'All MOSFETs|/products/mosfet-transistor|Pune Hub|/electronic-components-supplier-pune',
    canonicalUrl: 'https://miraitechnologies.net/power-mosfets-supplier-pune',
    robotsMeta: 'index, follow'
  },
  {
    slug: '/igbts-supplier-pune',
    city: 'Pune (IGBTs)',
    state: 'Maharashtra',
    isHQ: false,
    h1: 'IGBTs Supplier for Pune Industrial Drives & Auto Sector',
    metaTitle: 'IGBT Supplier Pune | Mirai Technologies Power Electronics',
    metaDescription: 'Discrete IGBTs & modules for Pune motor drives & welding machine repair in Bhosari & Chakan (FGL60N100, 75N60). 24-48h delivery from Mumbai.',
    primaryKeyword: 'igbts supplier pune',
    secondaryKeywords: 'igbt stockist pune, bhosari welding igbt, motor drive igbt pune',
    heroContent: '600V and 1200V discrete IGBTs and switching transistors delivered to Pune motor drive OEMs and industrial repair workshops in 24 to 48 hours.',
    introduction: 'Motor drive builders and industrial welding repair technicians in Bhosari and Chakan depend on heavy-duty IGBTs. Mirai Technologies supplies high-speed, low-Vce(sat) IGBTs with guaranteed authenticity shipped directly from Mumbai.\n\nFeatured IGBTs for Pune Buyers:\n- FGL60N100 (1000V 60A NPT IGBT for welding inverters)\n- 75N60 / 60N60 (600V 75A IGBT for high-frequency motor switching)',
    whyMirai: '24-48h transit from Mumbai. QC verified stock. Contact: +91 93213 98188.',
    productCategories: 'Discrete TO-247 IGBTs for power conversion and motor drive control.',
    targetIndustries: 'Motor Drive Manufacturing, Welding Inverter Repair, UPS Units',
    industriesWeServe: 'Supplying engineering units in Bhosari, Chakan, and Talegaon.',
    faqs: [{ q: 'Are FGL60N100 IGBTs available for immediate dispatch to Pune?', a: 'Yes, FGL60N100 IGBTs are stocked in Mumbai and dispatched same-day for Pune delivery.' }],
    internalLinks: 'All IGBTs|/products/igbts|Pune Hub|/electronic-components-supplier-pune',
    canonicalUrl: 'https://miraitechnologies.net/igbts-supplier-pune',
    robotsMeta: 'index, follow'
  },
  {
    slug: '/integrated-circuits-supplier-bengaluru',
    city: 'Bengaluru (ICs)',
    state: 'Karnataka',
    isHQ: false,
    h1: 'Integrated Circuits (ICs) Supplier for Bengaluru R&D Labs',
    metaTitle: 'Integrated Circuits Supplier Bengaluru | Mirai Tech R&D',
    metaDescription: 'ICs supplier for Bengaluru hardware startups & R&D labs in Electronic City & Peenya. Op-amps, comparators & interface ICs with 1-pc MOQ & 24-48h air delivery.',
    primaryKeyword: 'integrated circuits supplier bengaluru',
    secondaryKeywords: 'ic supplier bangalore, electronic city ic stockist, peenya op amp supplier',
    heroContent: 'Precision analog, logic, and interface ICs supplied to Bengaluru hardware startups and R&D labs with 1-piece MOQ and 24-48 hour air freight from Mumbai.',
    introduction: 'Engineers building prototype IoT boards and hardware units in Koramangala, Peenya, and Electronic City require single-piece IC availability without high minimum order quantities. Mirai Technologies supports Bengaluru R&D with fast air dispatch from Mumbai.\n\nFeatured ICs for Bengaluru Hardware Developers:\n- LM358L / LM358 (Dual Operational Amplifier)\n- LM339L / LM339 (Quad Comparator)\n- CH340G (USB-to-UART Serial Transceiver)\n- DS1307 (I2C Real-Time Clock IC)',
    whyMirai: '1-piece MOQ for prototyping. Overnight air freight to Bengaluru. Contact: sales@miraitechnologies.net.',
    productCategories: 'Linear ICs, Interface ICs, RTCs, and Logic devices in DIP and SOIC packages.',
    targetIndustries: 'Hardware Startups, IoT Devices, Aerospace R&D, University Labs',
    industriesWeServe: 'Serving hardware design teams across Electronic City, Peenya, and Koramangala.',
    faqs: [{ q: 'Can I order single IC samples for testing in my Bengaluru lab?', a: 'Yes, we offer single-unit ordering on catalog ICs for R&D testing.' }],
    internalLinks: 'All ICs|/products/integrated-circuit|Bengaluru Hub|/electronic-components-supplier-bengaluru',
    canonicalUrl: 'https://miraitechnologies.net/integrated-circuits-supplier-bengaluru',
    robotsMeta: 'index, follow'
  },
  {
    slug: '/microcontrollers-supplier-bengaluru',
    city: 'Bengaluru (Microcontrollers)',
    state: 'Karnataka',
    isHQ: false,
    h1: 'Microcontrollers Supplier for Bengaluru Embedded Ecosystem',
    metaTitle: 'Microcontrollers Supplier Bengaluru | Mirai Technologies',
    metaDescription: '8-bit & 32-bit Microcontrollers supplier for Bengaluru embedded design & IoT startups in Electronic City & HSR. 1-pc MOQ, overnight air dispatch.',
    primaryKeyword: 'microcontrollers supplier bengaluru',
    secondaryKeywords: 'mcu supplier bangalore, iot microcontroller bengaluru, embedded hardware components bangalore',
    heroContent: '8-bit, 16-bit, and 32-bit microcontrollers supplied from Mumbai stock to Bengaluru embedded engineers and IoT startups.',
    introduction: 'Bengaluru is India embedded engineering capital. Design hardware teams in HSR Layout and Whitefield require reliable microcontrollers with complete datasheet support and quick delivery. Mirai Technologies ships genuine MCUs via express air cargo from Mumbai.\n\nWhy Bengaluru MCU Developers Sourced from Mirai:\n- Single-piece sample orders for prototype PCB builds\n- Express 24-48 hour air shipment to Bengaluru\n- Verified silicon date codes with full batch traceability',
    whyMirai: 'Supporting Bengaluru embedded design labs. Zero MOQ policy for sample orders. Call +91 93213 98188.',
    productCategories: '8-bit and 32-bit MCUs, crystal oscillators, and EEPROM memory ICs.',
    targetIndustries: 'IoT Devices, Smart Energy Meters, Automotive Telematics, R&D Labs',
    industriesWeServe: 'Supplying embedded developers in Electronic City, HSR Layout, and Whitefield.',
    faqs: [{ q: 'How fast can MCU samples reach Koramangala or HSR Layout?', a: 'Overnight air freight delivers MCU orders to Bengaluru within 24 to 48 hours.' }],
    internalLinks: 'All Microcontrollers|/products/microcontrollers|Bengaluru Hub|/electronic-components-supplier-bengaluru',
    canonicalUrl: 'https://miraitechnologies.net/microcontrollers-supplier-bengaluru',
    robotsMeta: 'index, follow'
  },
  {
    slug: '/power-mosfets-supplier-chennai',
    city: 'Chennai (Power MOSFETs)',
    state: 'Tamil Nadu',
    isHQ: false,
    h1: 'Power MOSFETs Supplier for Chennai Automotive & EMS Plants',
    metaTitle: 'Power MOSFETs Supplier Chennai | Mirai Technologies EMS',
    metaDescription: 'Power MOSFET supplier for Chennai EMS & automotive plants in Sriperumbudur & Ambattur (IRFP4668, STP55NF06). Scheduled batch deliveries, GST invoices.',
    primaryKeyword: 'power mosfets supplier chennai',
    secondaryKeywords: 'sriperumbudur mosfet supplier, automotive mosfet chennai, irfp4668 supplier chennai',
    heroContent: 'Production-volume supply of N-channel and P-channel power MOSFETs delivered to EMS plants and automotive electronics factories in Sriperumbudur and Ambattur.',
    introduction: 'Contract electronic manufacturing (EMS) facilities in Sriperumbudur and Oragadam run volume SMT assembly lines for power supplies and automotive electronics. Mirai Technologies provides scheduled batch supply of power MOSFETs with volume pricing tiers and full GST invoice integration.\n\nFeatured MOSFET Lines for Chennai EMS:\n- IRFP4668 (200V 130A TO-247 MOSFET for power stages)\n- STP55NF06 (60V 50A TO-220 MOSFET for automotive electronics)\n- IRFP460 (500V 20A N-channel power MOSFET)',
    whyMirai: 'Volume price breaks & scheduled production shipments to Chennai. Contact: sales@miraitechnologies.net.',
    productCategories: 'Reel and tube packaging of power MOSFETs for SMT and THT assembly.',
    targetIndustries: 'EMS Manufacturing, Automotive Electronics, Industrial Power Units',
    industriesWeServe: 'Serving electronics factories in Sriperumbudur, Ambattur, and Oragadam.',
    faqs: [{ q: 'Do you offer reel packaging for automated SMT lines in Chennai?', a: 'Yes, surface-mount MOSFETs and ICs are supplied in original tape & reel packaging.' }],
    internalLinks: 'All MOSFETs|/products/mosfet-transistor|Chennai Hub|/electronic-components-supplier-chennai',
    canonicalUrl: 'https://miraitechnologies.net/power-mosfets-supplier-chennai',
    robotsMeta: 'index, follow'
  },
  {
    slug: '/integrated-circuits-supplier-chennai',
    city: 'Chennai (ICs)',
    state: 'Tamil Nadu',
    isHQ: false,
    h1: 'Integrated Circuits (ICs) Supplier for Chennai Electronics Corridors',
    metaTitle: 'Integrated Circuits Supplier Chennai | Mirai Tech EMS',
    metaDescription: 'Volume IC supplier for Chennai electronics assembly lines in Sriperumbudur & Ambattur. Op-amps, logic ICs & drivers (LM358, ULN2003) with GST e-way bills.',
    primaryKeyword: 'integrated circuits supplier chennai',
    secondaryKeywords: 'ic supplier chennai, sriperumbudur ic stockist, ambattur electronics components',
    heroContent: 'High-volume logic, interface, and operational amplifier ICs supplied to Chennai electronics assembly plants from Mumbai warehouse inventory.',
    introduction: 'High-volume production lines in Chennai require dependable IC deliveries with consistent date codes and clear tax billing. Mirai Technologies provides bulk reels and tubes of standard operational amplifiers, transceivers, and motor driver ICs to Chennai industrial zones.\n\nKey IC Lines for Chennai Production Lines:\n- LM358 / LM358L (Dual Op-Amp in DIP-8 and SOIC-8)\n- ULN2003 (7-Channel Darlington Transistor Array)\n- LM339 (Quad Comparator IC for control circuitry)',
    whyMirai: 'Scheduled batch shipping to Chennai EMS zones. 100% factory original. Call +91 93213 98188.',
    productCategories: 'Standard linear ICs, logic gates, and interface drivers in volume packaging.',
    targetIndustries: 'EMS Assembly Lines, Consumer Electronics, Industrial Automation',
    industriesWeServe: 'Supplying manufacturing corridors in Ambattur, Sriperumbudur, and Maraimalai Nagar.',
    faqs: [{ q: 'What is the bulk lead time for volume IC orders to Chennai?', a: 'Stock items ship within 24 hours of PO confirmation; air freight arrives in Chennai in 24-48 hours.' }],
    internalLinks: 'All ICs|/products/integrated-circuit|Chennai Hub|/electronic-components-supplier-chennai',
    canonicalUrl: 'https://miraitechnologies.net/integrated-circuits-supplier-chennai',
    robotsMeta: 'index, follow'
  },
  {
    slug: '/power-mosfets-supplier-delhi-ncr',
    city: 'Delhi NCR (Power MOSFETs)',
    state: 'Delhi',
    isHQ: false,
    h1: 'Power MOSFETs Supplier for Delhi NCR Inverter Manufacturers',
    metaTitle: 'Power MOSFETs Supplier Delhi NCR | Mirai Technologies',
    metaDescription: 'Anti-counterfeit power MOSFET supplier for Delhi NCR inverter & UPS manufacturers in Noida & Gurgaon (IRF3205, IRFP460, IRFP4668). 48h transit from Mumbai.',
    primaryKeyword: 'power mosfets supplier delhi ncr',
    secondaryKeywords: 'inverter mosfet supplier delhi, noida mosfet stockist, buy irf3205 delhi',
    heroContent: 'Anti-counterfeit N-channel power MOSFETs supplied to home inverter and UPS manufacturers in Noida, Gurgaon, Okhla, and Faridabad.',
    introduction: 'Inverter mainboard assembly lines in Noida Sector 63 and Okhla depend on high-current MOSFETs that can handle heavy inductive battery switching without premature breakdown. Mirai Technologies delivers 100% inspected, factory-original MOSFETs directly from Mumbai, bypassing regional grey-market risks.\n\nFeatured Inverter MOSFETs in Stock:\n- IRF3205 (55V 110A N-channel MOSFET for 12V inverter mainboards)\n- IRFP460 (500V 20A TO-247 MOSFET for high-voltage DC-DC stages)\n- IRFP4668 (200V 130A high-current MOSFET for heavy-duty UPS systems)',
    whyMirai: 'Zero grey-market risk. QC tested in Mumbai before dispatch. Contact: sales@miraitechnologies.net.',
    productCategories: 'TO-220 and TO-247 power MOSFETs for inverter and power supply assembly.',
    targetIndustries: 'Home Inverter Manufacturing, Online UPS Production, Solar Charge Controllers',
    industriesWeServe: 'Supplying manufacturing units in Noida, Gurgaon, Okhla, and Faridabad.',
    faqs: [{ q: 'Are IRF3205 MOSFETs tested for genuine silicon die parameters?', a: 'Yes, all MOSFET batches undergo parametric testing at our Mumbai QC center before stock entry.' }],
    internalLinks: 'All MOSFETs|/products/mosfet-transistor|Delhi NCR Hub|/electronic-components-supplier-delhi-ncr',
    canonicalUrl: 'https://miraitechnologies.net/power-mosfets-supplier-delhi-ncr',
    robotsMeta: 'index, follow'
  },
  {
    slug: '/diodes-rectifiers-supplier-delhi-ncr',
    city: 'Delhi NCR (Diodes)',
    state: 'Delhi',
    isHQ: false,
    h1: 'Diodes & Bridge Rectifiers Supplier for Delhi NCR Electronics',
    metaTitle: 'Diodes & Bridge Rectifiers Supplier Delhi NCR | Mirai Tech',
    metaDescription: 'Bridge rectifiers (MB6S, MB10S) & fast recovery diodes for Delhi NCR LED driver & power supply assembly in Okhla & Noida. Anti-counterfeit guaranteed.',
    primaryKeyword: 'diodes rectifiers supplier delhi ncr',
    secondaryKeywords: 'bridge rectifier supplier delhi, mb6s stockist noida, okhla diode supplier',
    heroContent: 'Surface-mount and through-hole bridge rectifiers, Schottky diodes, and surge protection devices delivered to Delhi NCR power supply and LED driver assembly lines.',
    introduction: 'LED driver and power adapter manufacturers in Okhla and Noida Sector 81 need cost-effective, high-reliability bridge rectifiers. Mirai Technologies supplies MB6S, MB10S, and fast recovery rectifiers with guaranteed authenticity and full GST tax billing.\n\nKey Rectifier Products for NCR Assembly:\n- MB6S / MB10S (0.5A 600V/1000V SMD Bridge Rectifiers)\n- 1N4007 / 1N5408 (General purpose rectifier diodes)\n- Fast recovery diodes for high-frequency SMPS stages',
    whyMirai: 'Direct factory-traceable stock shipped from Mumbai. Call +91 93213 98188.',
    productCategories: 'SMD and THT bridge rectifiers, Zener diodes, and Schottky rectifiers.',
    targetIndustries: 'LED Driver Assembly, SMPS Power Supplies, Consumer Chargers',
    industriesWeServe: 'Serving assembly facilities in Okhla, Noida, Gurgaon, and Ghaziabad.',
    faqs: [{ q: 'Can you supply MB10S bridge rectifiers in 3,000-piece tape & reel for Noida SMT lines?', a: 'Yes, full factory tape & reel packaging is stocked for automated SMT placement.' }],
    internalLinks: 'All Diodes|/products/diodes-rectifiers|Delhi NCR Hub|/electronic-components-supplier-delhi-ncr',
    canonicalUrl: 'https://miraitechnologies.net/diodes-rectifiers-supplier-delhi-ncr',
    robotsMeta: 'index, follow'
  },
  {
    slug: '/power-mosfets-supplier-ahmedabad',
    city: 'Ahmedabad (Power MOSFETs)',
    state: 'Gujarat',
    isHQ: false,
    h1: 'Power MOSFETs Supplier for Ahmedabad & Gujarat Solar Sector',
    metaTitle: 'Power MOSFETs Supplier Ahmedabad | Mirai Technologies Gujarat',
    metaDescription: 'High-voltage Power MOSFET supplier for Gujarat solar inverter OEMs in Sanand & Changodar (STW4N150, IRFP460). 24-48h dispatch from Mumbai.',
    primaryKeyword: 'power mosfets supplier ahmedabad',
    secondaryKeywords: 'solar inverter mosfet ahmedabad, high voltage mosfet gujarat, sanand mosfet supplier',
    heroContent: 'High-voltage N-channel power MOSFETs (500V-1500V) supplied to solar inverter manufacturers and power conversion plants in Ahmedabad, Sanand, and Changodar.',
    introduction: 'Solar string inverter manufacturers in Changodar and Sanand build high-efficiency DC-DC boost stages and MPPT trackers requiring robust high-voltage MOSFETs. Mirai Technologies provides tested power MOSFETs with 24-48 hour delivery from Mumbai.\n\nFeatured Solar Power MOSFETs:\n- STW4N150 (1500V 4A TO-247 N-channel MOSFET for high-voltage auxiliary power)\n- IRFP460 (500V 20A TO-247 MOSFET for inverter boost conversion)\n- IRFP4668 (200V 130A MOSFET for battery-tied solar storage inverters)',
    whyMirai: 'High-voltage MOSFET stock in Mumbai. RoHS & REACH compliance certificates available. Contact: sales@miraitechnologies.net.',
    productCategories: '500V to 1500V N-channel MOSFETs in TO-247 and TO-220 packages.',
    targetIndustries: 'Solar Inverter OEMs, Industrial Power Supplies, High-Voltage DC-DC Converters',
    industriesWeServe: 'Serving power electronics manufacturers in Sanand, Changodar, Naroda, and Vatva.',
    faqs: [{ q: 'Do you stock 1500V rated MOSFETs for solar auxiliary power circuits in Gujarat?', a: 'Yes, STW4N150 (1500V 4A) MOSFETs are held in stock for auxiliary supply stages.' }],
    internalLinks: 'All MOSFETs|/products/mosfet-transistor|Ahmedabad Hub|/electronic-components-supplier-ahmedabad',
    canonicalUrl: 'https://miraitechnologies.net/power-mosfets-supplier-ahmedabad',
    robotsMeta: 'index, follow'
  },
  {
    slug: '/igbts-supplier-ahmedabad',
    city: 'Ahmedabad (IGBTs)',
    state: 'Gujarat',
    isHQ: false,
    h1: 'IGBTs Supplier for Ahmedabad Solar Inverters & Heavy Drives',
    metaTitle: 'IGBT Supplier Ahmedabad | Mirai Technologies Solar Power',
    metaDescription: 'Discrete 600V-1200V IGBTs for Ahmedabad solar inverter & industrial drive OEMs in Sanand & GIDC Naroda (FGL60N100, 75N60). Fast Mumbai dispatch.',
    primaryKeyword: 'igbts supplier ahmedabad',
    secondaryKeywords: 'solar inverter igbt gujarat, fgl60n100 ahmedabad, heavy drive igbt supplier ahmedabad',
    heroContent: '600V and 1200V discrete IGBTs supplied to solar inverter builders and heavy industrial drive manufacturers in Ahmedabad and Vadodara.',
    introduction: 'Solar inverter power bridges and three-phase motor drives built in Sanand and Naroda demand high-efficiency IGBTs with low conduction loss. Mirai Technologies supplies factory-original IGBTs with 24-48 hour shipping from Mumbai.\n\nFeatured IGBTs for Gujarat OEMs:\n- FGL60N100 (1000V 60A NPT Trench IGBT for high-power inverters)\n- 75N60 / 60N60 (600V 75A IGBT for high-frequency switching)',
    whyMirai: '24-48h dispatch from Mumbai warehouse. Complete e-way bill documentation. Call +91 93213 98188.',
    productCategories: 'TO-247 discrete IGBTs and fast recovery diodes for power conversion.',
    targetIndustries: 'Solar Inverters, Industrial VFD Drives, Induction Heating',
    industriesWeServe: 'Supplying OEMs across Ahmedabad, Sanand, Vadodara, and Rajkot.',
    faqs: [{ q: 'What is the transit time for IGBT shipments to Sanand industrial park?', a: 'Express surface/air shipments arrive at Sanand within 24 to 48 hours of Mumbai dispatch.' }],
    internalLinks: 'All IGBTs|/products/igbts|Ahmedabad Hub|/electronic-components-supplier-ahmedabad',
    canonicalUrl: 'https://miraitechnologies.net/igbts-supplier-ahmedabad',
    robotsMeta: 'index, follow'
  },
  {
    slug: '/integrated-circuits-supplier-hyderabad',
    city: 'Hyderabad (ICs)',
    state: 'Telangana',
    isHQ: false,
    h1: 'Integrated Circuits (ICs) Supplier for Hyderabad Defence & PSUs',
    metaTitle: 'Integrated Circuits Supplier Hyderabad | Mirai Tech CoC',
    metaDescription: 'Factory-traceable ICs with Certificate of Conformance (CoC) for Hyderabad defence & aerospace PSUs in ECIL & Balanagar (LM358, LM339, OP07). Air express.',
    primaryKeyword: 'integrated circuits supplier hyderabad',
    secondaryKeywords: 'defence ic supplier hyderabad, ecil ic stockist, certificate of conformance ic hyderabad',
    heroContent: 'Traceable integrated circuits, operational amplifiers, and interface ICs supplied with Certificate of Conformance (CoC) to Hyderabad defence and aerospace contractors.',
    introduction: 'Quality control protocols at defence contractors in Balanagar and ECIL require complete batch provenance and Certificate of Conformance documentation. Mirai Technologies supplies factory-inspected ICs with verified lot codes shipped via express air freight from Mumbai.\n\nFeatured IC Lines for Defence & Aerospace PSUs:\n- LM358 / OP07 (Low-noise, precision operational amplifiers)\n- LM339 (Quad voltage comparator for signal conditioning)\n- ULN2003 (7-channel peripheral driver IC)\n- Obsolete IC sourcing for long-lifecycle legacy programs',
    whyMirai: 'Certificate of Conformance (CoC) provided. Air express 24-48h delivery to Hyderabad. Contact: sales@miraitechnologies.net.',
    productCategories: 'Precision linear ICs, logic series, and interface transceivers.',
    targetIndustries: 'Defence PSUs, Aerospace Subcontractors, Medical Electronics',
    industriesWeServe: 'Serving high-reliability electronics units in ECIL, Balanagar, and Cherlapally.',
    faqs: [{ q: 'Can you supply lot-traceable ICs with manufacturer date codes to Hyderabad PSUs?', a: 'Yes, lot traceability details and CoC documentation are supplied with quality-audited shipments.' }],
    internalLinks: 'All ICs|/products/integrated-circuit|Hyderabad Hub|/electronic-components-supplier-hyderabad',
    canonicalUrl: 'https://miraitechnologies.net/integrated-circuits-supplier-hyderabad',
    robotsMeta: 'index, follow'
  },
  {
    slug: '/power-mosfets-supplier-coimbatore',
    city: 'Coimbatore (Power MOSFETs)',
    state: 'Tamil Nadu',
    isHQ: false,
    h1: 'Power MOSFETs Supplier for Coimbatore Motor Drive & VFD Sector',
    metaTitle: 'Power MOSFETs Supplier Coimbatore | Mirai Technologies',
    metaDescription: 'Power MOSFET supplier for Coimbatore motor, pump & VFD repair workshops in Ganapathy & SIDCO (IRFP460, IRFP4668). 48h courier from Mumbai.',
    primaryKeyword: 'power mosfets supplier coimbatore',
    secondaryKeywords: 'vfd repair mosfet coimbatore, pump drive mosfet coimbatore, irfp460 coimbatore',
    heroContent: 'Power MOSFETs supplied to motor controller OEMs, pump manufacturers, and VFD repair workshops in Coimbatore, Ganapathy, and SIDCO.',
    introduction: 'Motor drive builders and industrial repair workshops in SIDCO industrial estate require robust power MOSFETs for switching mainboards and auxiliary power supplies. Mirai Technologies provides genuine, tested power MOSFETs with 48-hour delivery from Mumbai.\n\nKey MOSFET Lines for Coimbatore Engineering:\n- IRFP460 (500V 20A TO-247 N-channel MOSFET for industrial SMPS)\n- IRFP4668 (200V 130A MOSFET for high-power DC motor drivers)\n- STP55NF06 (60V 50A MOSFET for low-voltage pump controllers)',
    whyMirai: '48h express delivery to Coimbatore. Low MOQ for repair workshops. Call +91 93213 98188.',
    productCategories: 'N-channel and P-channel power MOSFETs in TO-220 and TO-247 packages.',
    targetIndustries: 'Pump Manufacturing, VFD Repair Workshops, Textile Machinery Control',
    industriesWeServe: 'Serving machinery builders and repairers in Ganapathy, SIDCO, and Peelamedu.',
    faqs: [{ q: 'Do you sell small quantities of MOSFETs for VFD repair in Coimbatore?', a: 'Yes, repair workshops can order low MOQ quantities directly with 48-hour dispatch.' }],
    internalLinks: 'All MOSFETs|/products/mosfet-transistor|Coimbatore Hub|/electronic-components-supplier-coimbatore',
    canonicalUrl: 'https://miraitechnologies.net/power-mosfets-supplier-coimbatore',
    robotsMeta: 'index, follow'
  }
];

// Combine all 100 original city pages + 17 matrix pages
const combined = [...original100Pages, ...matrixPages];

const outputPath = path.join(__dirname, '../src/data/cityPages.json');
fs.writeFileSync(outputPath, JSON.stringify(combined, null, 2), 'utf-8');
console.log(`Successfully restored all ${combined.length} city & matrix pages (${original100Pages.length} original cities across 22 states + 17 matrix pages)!`);
